[server]
port = 8501
headless = true
runOnSave = true
fileWatcherType = "poll"
maxUploadSize = 200

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[client]
toolbarMode = "minimal"

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[logger]
level = "info"

[runner]
fastReruns = false
